### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by valeriykundas** [daryasy/weather-app#1]

**Comment by valeriykundas** [comment]
Can you please add an instructions on how to set it up?

**Comment by pythad** [comment]
As far as I know, it hasn't been deployed anywhere yet)

Why wouldn't you just check weather at some online resource?

**Comment by valeriykundas** [comment]
But there has to be a way to run it locally. That's what I'm asking for.

I'm interested in seeing what @daryasy can do.
